### ISSUE TITLE
Incompatible with Git

### ISSUE THREAD

**Issue by davidrivers** [vigetlabs/capistrano_rsync_with_remote_cache#1]
This gem supposedly works with Git "2.1.0 or higher", but the following issue remains while attempting to cap deploy with this gem installed and ":deploy_via" set to ":rsync_with_remote_cache":

/Users/david/.gem/ruby/1.8/gems/capistrano_rsync_with_remote_cache-2.3.2/lib/capistrano/recipes/deploy/strategy/rsync_with_remote_cache.rb:78:in `command': private method`chomp' called for nil:NilClass (NoMethodError)

Apparently, according to the comments in rsync_with_remote_cache.rb, lines 71-72:

```
    # FIXME: The above logic only takes place if the SCM is Subversion. At some point, similar logic
    # will probably be necessary for Git and other SCMs we might use.
```

**Comment by mcornick** [comment]
There was indeed a bug here (fixed in version 2.3.3) but the code in question only runs if the SCM is subversion, either by virtue of it being the default SCM, or by `set :scm, :subversion` being explicitly set in the Capfile.

In order to use Capistrano with Git (whether or not you are using this gem) you must set `set :scm, :git` in the Capfile.
